# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mnn_correct <- function(x, batch, k, nmads, iterations, trim) {
    .Call('_mnncorrect_ref_mnn_correct', PACKAGE = 'mnncorrect.ref', x, batch, k, nmads, iterations, trim)
}

robust_average <- function(x, iterations, trim) {
    .Call('_mnncorrect_ref_robust_average', PACKAGE = 'mnncorrect.ref', x, iterations, trim)
}

