# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute <- function(x, batch, num_batches, k, steps, input_order) {
    .Call('_mnncorrect_ref_compute', PACKAGE = 'mnncorrect.ref', x, batch, num_batches, k, steps, input_order)
}

